import photo1 from "../assets/3.Proje/canva1.jpg";
import photo2 from "../assets/3.Proje/canva2.jpg";
import photo3 from "../assets/3.Proje/canva3.jpg";
import photo4 from "../assets/3.Proje/canva4.jpg";
import photo5 from "../assets/3.Proje/canva5.jpg";
import photo6 from "../assets/3.Proje/canva6.jpg";
import photo7 from "../assets/3.Proje/canva7.jpg";
import photo8 from "../assets/3.Proje/canva8.jpg";
import photo9 from "../assets/3.Proje/canva9.jpg";
import photo10 from "../assets/3.Proje/canva10.jpg";
import photo11 from "../assets/3.Proje/canva11.jpg";
import photo12 from "../assets/3.Proje/canva12.jpg";
import photo13 from "../assets/3.Proje/canva13.jpg";
import photo14 from "../assets/3.Proje/canva14.jpg";
import photo15 from "../assets/3.Proje/canva15.jpg";
import photo16 from "../assets/3.Proje/canva16.jpg";
import photo17 from "../assets/3.Proje/canva17.jpg";
import photo18 from "../assets/3.Proje/canva18.jpg";
import photo19 from "../assets/3.Proje/canva19.jpg";
import photo20 from "../assets/3.Proje/canva20.jpg";
import photo21 from "../assets/3.Proje/canva21.jpg";
import photo22 from "../assets/3.Proje/canva22.jpg";
import photo23 from "../assets/3.Proje/canva23.jpg";
import photo24 from "../assets/3.Proje/canva24.jpg";
import photo25 from "../assets/3.Proje/canva25.jpg";
import photo26 from "../assets/3.Proje/canva26.jpg";
import photo27 from "../assets/3.Proje/canva27.jpg";
import photo28 from "../assets/3.Proje/canva28.jpg";

const images = [
  { src: photo1 },
  { src: photo2 },
  { src: photo3 },
  { src: photo4 },
  { src: photo5 },
  { src: photo6 },
  { src: photo7 },
  { src: photo8 },
  { src: photo9 },
  { src: photo10 },
  { src: photo11 },
  { src: photo12 },
  { src: photo13 },
  { src: photo14 },
  { src: photo15 },
  { src: photo16 },
  { src: photo17 },
  { src: photo18 },
  { src: photo19 },
  { src: photo20 },
  { src: photo21 },
  { src: photo22 },
  { src: photo23 },
  { src: photo24 },
  { src: photo25 },
  { src: photo26 },
  { src: photo27 },
  { src: photo28 },
];

export default images;
